### ISSUE TITLE
freeze map after navigation

### ISSUE THREAD

**Issue by enniel** [react-community/react-native-maps#1175]
[Screen record](https://youtu.be/xZqGxxzzaKk)

**Comment by souzaguilherme** [comment]
Were you able to fix this problem?

**Comment by VickyKoblinski** [comment]
I'm having the same issue on Android. The initial navigation to the page worked as expected, but navigating "back" caused the map to freeze. I also had to be sure to make sure my callback for going back to the maps page first call Keyboard.dismiss() before returning, otherwise the map would zoom out/start rendering before the keyboard can dismiss itself. 

Removing cacheEnabled fixed the freezing issue. 

"react-native": "0.42.3"
"react-native-maps": "^0.15.2"
"react-navigation": "^1.0.0-beta.9"

**Comment by dinesh8055** [comment]
I set the cacheEnabled to false but still the problem persists. Any other possible fixes?

**Comment by salbatore** [comment]
I have de same problem, any solution?.

**Comment by dinesh8055** [comment]
You can try Reset action in react navigation. Probably, the react-navigation stacks the maps which results in this effect. I am sure it is not an issue with this package.

**Comment by Masoodt** [comment]
@VickyKoblinski Thank you so much Dear Vicky, You have solved my problem and saved my life!

**Comment by alvelig** [comment]
Seems resolved.

**Comment by juliancorrea** [comment]
In my case, it was missing <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>.

**Comment by dapHead** [comment]
> Android'de aynı sorunu yaşıyorum. Sayfadaki ilk gezinme beklendiği gibi çalıştı, ancak "geri" gezinmek haritanın donmasına neden oldu. Ayrıca geri dönmeden önce haritalar sayfasına geri dönmek için geri arama yaptığımdan emin olmalıydım. Aksi takdirde, harita klavyenin kendini atlatmadan önce görüntülemeyi uzaklaştırır / başlatır.
> 
> CacheEnabled'ın kaldırılması, donma sorununu giderdi.
> 
> "tepki-yerel": "0.42.3" 
> "tepki-yerel haritalar": "^ 0.15.2" 
> "tepki-gezinti": "^ 1.0.0-beta.9"

thank you so much <3
