### ISSUE TITLE
File RCTConvert+MapKit.m not found

### ISSUE THREAD

**Issue by ignacioola** [react-community/react-native-maps#1213]
### Issue Description

File not found error after building project on XCode.

### Steps to Reproduce / Code Snippets

1. Install react-native-maps
    ```
    yarn add react-native-maps
    ```
2. Link react-native-maps
    ```
    react-native link react-native-maps
    ```
3. Open XCode project
    ```
    open ios/MyProject.xcproject
    ```
4. Build the project with `⌘ + B`, crashing with the following output: 
    ```
    clang: error: no such file or directory: 
    '/Users/username/Projects/MapsTest/node_modules/react-native-maps/lib/ios/AirMaps/RCTConvert+MapKit.m'
    clang: error: no input files   
    ```

#### Expected Results

Successful build

### Additional Information

* React Native Maps version: 0.14.0
* React Native version: 0.43.0
* Platform(s): iOS
* No other libraries installed

**Comment by simonmitchell** [comment]
This needs changing in the project file and various other places, it was renamed here but the contributors project file was not committed with the change. Will submit a PR now: https://github.com/airbnb/react-native-maps/commit/4926f5b53fac8e1ab9aaf877e81048e262dee8aa

**Comment by simonmitchell** [comment]
PR can be seen here: https://github.com/airbnb/react-native-maps/pull/1214

**Comment by ignacioola** [comment]
Great @simonmitchell! Hope your PR gets merged soon.

**Comment by tuneZola** [comment]
Yeah, this is kind of a blocker for people upgrading. Need to also bump up the dependency versions, still wants React 15.4, and RN 0.43.2 wants 16 alpha.

**Comment by bberthelemy** [comment]
Hi, thx @simonmitchell for your PR, you just forgot to update xcodeproj references. I created a new PR about it => #1224

**Comment by rh389** [comment]
This is a dup of https://github.com/airbnb/react-native-maps/issues/1193 and there's another PR https://github.com/airbnb/react-native-maps/pull/1195 (I think that makes three!)

**Comment by simonmitchell** [comment]
@bberthelemy I shouldn't have missed anything, you just happen to have more changes to your project file which I can only assume are from changes you've made on your fork :)

**Comment by tonygriv** [comment]
I have no such file or directory: react-native/React/Views/RCTConvert+MapKit.m error. What should I do?

 "react-native": "0.44.2",
"react-native-maps": "0.15.2"

**Comment by rh389** [comment]
That was part of the maps component bundled with RN, which has now been removed from RN. You can remove your references to it - it's not needed for react-native-maps.

**Comment by tonygriv** [comment]
@rh389, and we are these references?

**Comment by rh389** [comment]
Since the error is showing a full path like that, my guess is that it's referenced in your project file, or maybe the project file of another dependency, or maybe you're using CocoaPods and haven't updated your installation since updating RN. You'll have to have a look around - a text search on your project root should show it up.

All I can say for sure is that file was part of `react-native` in 0.43 and was removed in 0.44, and clearly you have something still looking for it despite using 0.44. The file at the path you mention is nothing to do with `react-native-maps` (since https://github.com/airbnb/react-native-maps/pull/1138) - it just happens to have the same name as the file in the OP's issue (which ironically is the reason the one in `react-native-maps` was [renamed](https://github.com/airbnb/react-native-maps/commit/4926f5b53fac8e1ab9aaf877e81048e262dee8aa), which caused the OP's issue!).

**Comment by thelitlej** [comment]
I get this error, but i cant find the reference anywhere in the project, i'm searching for RCTConvert+Mapkit and it does not find anything. Sometimes the error disappears and everything works like it should. When i restart Xcode it appears again. Can this be some kind of a cache problem?

**Comment by itinance** [comment]
Anything we can do? We faced this issue also on a green field application based on RN 0.45

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
