### ISSUE TITLE
onPress mapview doest return coordinate

### ISSUE THREAD

**Issue by benyliantriana** [react-community/react-native-maps#1286]
I want to draw marker when map is pressed. When i log the onPress(console) doesnt give return coordinate but when I use onRegionChange it does return coordinate. I use this lib in android (react-native project).
`onRegionChange={(region) => {
             console.log(region);
           }}`

perfectly works

`onPress={(coordinate) => {
             console.log(coordinate);
           }}`

doesnt work.
Somebody help me.
Great Project by airbnb!!! thanks
```

**Comment by zuber303** [comment]
It doesn't work in my app too.

**Comment by benyliantriana** [comment]
its working by using `e.nativeEvent.coordinate`
so the log is `console.log(e.nativeEvent.coordinate)`
@zuber303

**Comment by jimfilippou** [comment]
`onPress={(e.nativeEvent.coordinate) => { console.log(e.nativeEvent.coordinate) }}` doesn't work

**Comment by igorbrandao** [comment]
Thanks @benyliantriana, this is annoying... The way that MapView api is written today leads us to believe that `{coordinate, point}` params get injected directly to onPress callback but it does not. To make matters worse, when you try to log what params you truly get the app crashes with `there was a problem sending log messages to your development environment` because `nativeEvent` object is way too large for log stream, leaving us stranded as to how to get to the params until getting here. Why make the api docs unclear?

**Comment by EhsanSarshar** [comment]
to know what's inside received object you can easily console.log() or alert() it.
and because it have cyclic data you can use following library to print it's content
```
import {decycle} from 'json-cyclic'

function onPress(data) {
    console.log(JSON.stringfy(decycle(data), null, '\t'))
}
```

**Comment by felixrolando** [comment]
> `onPress={ (event) => console.log(event.nativeEvent.coordinate) }` **Worked for me**

Thanks
