### ISSUE TITLE
The following build commands failed

### ISSUE THREAD

**Issue by lyz1991** [react-community/react-native-maps#1863]
CompileC /Users/yunzhaoliu/Desktop/abc/myApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/RCTConvert+AirMap.o AirMaps/RCTConvert+AirMap.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
my reactnative version:0.51

**Comment by wkoutre** [comment]
@lyz1991 Go through the linking process manually -- don't rely on / trust `react-native-link react-native-maps`.

For me, this was the issue. I manually added `AirMaps.xcodeproj` to my XCode project's Libraries folder, the `AirGoogleMaps` folder to the root directory of the project, added `LibAirMaps.a` to `Linked Frameworks and Libraries` and have `pod 'GoogleMaps'` in my Podfile.

**Comment by alvelig** [comment]
Delete ios/build folder

**Comment by lyz1991** [comment]
@wkoutre 
I have done what you say，but I get more wrongs
such as 
In module 'MapKit' imported from /Users/yunzhaoliu/Desktop/abc/myApp/node_modules/react-native-maps/lib/ios/AirMaps/RCTConvert+AirMap.h:7:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/System/Library/Frameworks/MapKit.framework/Headers/MKTypes.h:13:5: note: 'MKMapTypeStandard' declared here
    MKMapTypeStandard = 0,
    ^
1 error generated. 
	CompileC /Users/yunzhaoliu/Desktop/abc/myApp/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/RCTConvert+AirMap.o AirMaps/RCTConvert+AirMap.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/test.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by lyz1991** [comment]
@alvelig 
Can the conponents support GeoCode ?

**Comment by alvelig** [comment]
You can use this component, for example: https://github.com/devfd/react-native-geocoder

**Comment by dylan-dinh** [comment]
Hello,

I am having almost the same issue I guess : 
`The following build commands failed:
	CompileC build/Build/Intermediates.noindex/we_are_open.build/Debug-iphonesimulator/we_are_open.build/Objects-normal/x86_64/AppDelegate.o we_are_open/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

I tried to remove de ios/build folder and run again : `react-native run-ios` and same error as above.
I am getting more errors due to this I guess

`The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64
(1 command with analyzer issues)`


`Installing build/Build/Products/Debug-iphonesimulator/we_are_open.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

`Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/we_are_open.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

thanks for help

**Comment by Juniper11** [comment]
@wkoutre how do you manually add LibAirMaps.a?  I can't find it anywhere.
