### ISSUE TITLE
Error On Pod install

### ISSUE THREAD

**Issue by Hemantsolanki103** [react-community/react-native-maps#1943]
Hi Team,

When I run command "Pod install", its give me below error(I have given console log). Please check this issue.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/hemantsolanki/Library/Android/sdk/tools in PATH, mode 040777
Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.3.1) is higher than the version of the current executable (1.2.0). Incompatibility issues may arise.
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-google-maps` from `../../`
Fetching podspec for `react-native-maps` from `../../`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
Downloading dependencies
Installing GoogleMaps (2.5.0)

[!] Error installing GoogleMaps
[!] /usr/bin/curl -f -L -o /var/folders/gn/kcpmksw13nngzfgxb27ftxsm0000gp/T/d20180106-1391-b5dcoe/file.tgz https://dl.google.com/dl/cpdc/6e5f7d9da3112ca6/GoogleMaps-2.5.0.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
**curl: (22) The requested URL returned error: 403 Forbidden**

Thanks & Regards,
Hemant Solanki

**Comment by alvelig** [comment]
Maybe the problem is in your pod file. We can't reproduce this issue without a reproducible example.

**Comment by rborn** [comment]
@Hemantsolanki103 it seems to be network failure (temporary on google side or your network)
You can see below the result I get.

I will close this issue because it doesn't respect the template. I'm sorry but we do this in our free time so we need your help to be able to help.

~~~
curl -I https://dl.google.com/dl/cpdc/6e5f7d9da3112ca6/GoogleMaps-2.5.0.tar.gz
HTTP/2 200 
accept-ranges: bytes
cache-control: public,max-age=86400
content-length: 46187248
content-type: application/octet-stream
etag: "182308"
last-modified: Mon, 23 Oct 2017 06:38:20 GMT
server: downloads
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
date: Mon, 08 Jan 2018 15:25:29 GMT
alt-svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"


~~~
