### ISSUE TITLE
Is it possible to block user interaction with Map?

### ISSUE THREAD

**Issue by lucasharada** [react-community/react-native-maps#1961]
The docs doesn't mention anything about it, but I would like to block the user interaction with the Map itself, only allow the interaction with the Marker.

**Comment by rborn** [comment]
No issue template, closing, sorry.

**Comment by alvelig** [comment]
Set constant region.

OR

Center your map on the marker coordinate, overlay your map with a view, and in the center of the view set your "marker" and thus you achieve what you want.

**Comment by criestlav** [comment]
Hi!
How can i set constant region?

Thank you!

**Comment by morksinaanab** [comment]
no issue template? It seems a pretty obvious feature request though :-) I haven't built the module, but I understand the request. I also need it. 

I did look at some alternatives:

1. Wrap the MapView in a `View` with property [pointerEvents="none"](url) works.	`<View pointerEvents="none">`
2. Just add the property `pointerEvents="none" to the MapView works as well. But including all the props you pass to the MapView might not be something that the module will keep supporting.
3. An third alternative might be to make a snapshot of the map and show that, but can you do that without rendering the map? https://github.com/react-community/react-native-maps#take-snapshot-of-map. I haven't tried that. It should give you the opportunity to use an image instead of map though.

**Comment by OlegNovosad** [comment]
There is more "map-like" solution: disable `pitch`, `rotation` and `zoom` for the map

```js
<MapView pitchEnabled={false} rotateEnabled={false} zoomEnabled={false} ... />
```

**Comment by ujangmisbah** [comment]
@OlegNovosad thank you, this is very helpful

**Comment by jmada** [comment]
@OlegNovosad thank you so much!

**Comment by BrodaNoel** [comment]
@OlegNovosad be careful with your proposal because that won't allow the user to scroll in a ScrollView.
If the user put the finger on top of the map and move it, the ScrollView won't scroll because the MapView is catching the finger gesture.

The better option is wrapping the MapView with a View with pointerEvents="none" prop

**Comment by ktanoooo** [comment]
thank you

```tsx
const coodinate = { latitude: xxx, longitude: xxx }

<View pointerEvents='none'>
  <MapView
    provider={PROVIDER_GOOGLE}
    initialRegion={coodinate}
    pitchEnabled={false}
    rotateEnabled={false}
    zoomEnabled={false}
    scrollEnabled={false}
  >
    <Marker
      coordinate={coodinate}
    />
  </MapView>
</View>
```
