### ISSUE TITLE
Use Google Maps in iOS

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-community/react-native-maps#1973]
I have installed react-native-maps library and successfully used map in my project. In android it is using Google Maps but in ios it's using MapKit (I think). So now how do I use Google Maps in ios iPhone device too. Please help

**Comment by alvelig** [comment]
See `provider` props and follow the docs (See https://github.com/react-community/react-native-maps/blob/master/docs/installation.md#get-a-google-maps-api-key)

**Comment by alvelig** [comment]
@ShaikhKabeer you did not follow the docs. Follow the docs and install GoogleMaps SDK and so on.

**Comment by jeffreymendez1993** [comment]
The docs are bad and barely work @alvelig

**Comment by rborn** [comment]
@jeffreymendez1993 feel free to raise a PR with better docs 😉  
Thats why we're a community.

**Comment by jeffreymendez1993** [comment]
@rborn Thanks will do. I probably should not have said bad but instead could use more detail to eliminate the install part. After a couple hours of being frustrated my mind was warped and I am just over here like this is CRAP since I have installed Gmaps on iOS on multiple projects using this library haha!. Ill try to be more insightful and contribute instead of roaring and barking.

**Comment by MarshMelon** [comment]
I hame problem with "!Unknown type name 'RCTBubblingEventBlock'"... Does Anybody Know The Solution To This Problem?
