### ISSUE TITLE
Is it possible to use with CRNA without ejecting?

### ISSUE THREAD

**Issue by tnrich** [react-community/react-native-maps#1981]
Hey there,

I'm just wondering if I'll need to "eject" my create-react-native-app project in order to use the react-native-maps?

It looks like in order to have access to say the build.gradle file I'll need to eject but I was wondering if anyone has used CRNA and this map component without ejecting?

Thanks!

**Comment by alvelig** [comment]
If not using Expo API, then yes, you will have to eject. Using Expo API you will have react-native-maps already bundled in Expo API, but with a minor version of react-native-maps.

**Comment by pcooney10** [comment]
@tnrich as @alvelig said, there is no need to eject from CRNA / Expo to use this . All you have to do is `import { MapView } from 'expo'` instead of `import MapView from 'react-native-maps'` and you get to skip all of the Podfile/gradle stuff. [Expo Docs](https://docs.expo.io/versions/latest/sdk/map-view.html)

**Comment by tnrich** [comment]
Awesome thanks @pcooney10! I got it working :)
