### ISSUE TITLE
[Android] Blank map on emulator, works on real device

### ISSUE THREAD

**Issue by arnsa** [react-community/react-native-maps#2028]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.53.0
react: 16.2.0
react-native-maps: 0.20.1

### Steps to Reproduce

Try to render map like this https://pastebin.com/8Xksi0We (I pasted the code to pastebin, because github wasn't displaying the code correctly for some reason).

### Expected Behavior

I should google maps on both, Android emulator and real device.

### Actual Behavior

Everything works as expected on real Android device but I see blank map with Google logo at the bottom on Android Nexus 5 emulator.

https://i.imgur.com/MvXWl3v.png

**Comment by rborn** [comment]
@arnsa you need an emulator that has google play services.

**Comment by arnsa** [comment]
@rborn I am not sure why you closed the issue, because my emulator DOES have google play services and they're updated to the latest version.

**Comment by rborn** [comment]
@arnsa as long as the google logo is rendered, it means the module works fine but there is a problem either with the api key or a wrong emulator.

I closed the issue because there lots of similar issues already. This would be one of them, but please search by yourself and let us know if you have it fixed: https://github.com/react-community/react-native-maps/issues/1877

**Comment by arnsa** [comment]
@rborn okay, launching app on emulator with API 25 fixed the issue. Thanks!
