### ISSUE TITLE
Project using gradle 3, but not mentioning that in installation instructions resulting to multiple issues

### ISSUE THREAD

**Issue by mauron85** [react-community/react-native-maps#2180]
### Is this a bug report?

Yes. For unknown reasons react-native-maps decided to use gradle 3, even though tools like `react-native init` are creating new project with gradle 2. However installation instructions are not mentioning that user is forced to update `com.android.tools.build:gradle` to version 3.

In other case build will fail with:

```
A problem occurred evaluating project ':react-native-maps'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

Another issue is incompatibility with other packages that are built with gradle 2. Like following issue:
https://github.com/mauron85/react-native-background-geolocation/issues/176

I really wish that react-native-maps follows react-native init defautls.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

react-native: 0.55.0
react-native-maps: 0.21.0

### Steps to Reproduce

1. create new project:
`react-native init mymapproject`
2. add react-native-maps
`yarn add react-native-maps`
3. follow install instructions
4. build project
`./gradlew build`

### Expected Behavior

project will build

### Actual Behavior

project build fails with:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmpProject/node_modules/react-native-maps/lib/android/build.gradle' line: 46

* What went wrong:
A problem occurred evaluating project ':react-native-maps'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by marcferna** [comment]
@mauron85 We are facing the same issue so we had to downgrade to `react-native-maps` version `0.20.1`

**Comment by mauron85** [comment]
Completely missing information how to switch to gradle 3. This arcticle covers it:

https://medium.com/bam-tech/boost-compilation-time-of-your-react-native-or-android-app-with-the-latest-build-tools-a3d5d398ed33

**Comment by rborn** [comment]
@mauron85 fancy a PR for the installation docs? 😊

**Comment by mauron85** [comment]
@rborn normally I would. But I have personal issue with this gradle 3 switch. :) I just don't like it. IMO it's no worth the hassle of updating `build.gradle`, `gradle-wrapper.properties`... I guess the only reason for switch was improvement build speed, but considering it already broke compatibility with other packages and lot of manual steps to make it work. No thank you.

**Comment by lachenmayer** [comment]
I have had someone separately reach out to me in private with this issue.
The project should definitely be using Gradle 2 if that's the React Native default.
+1 to simply reverting #2096, it's a clean change.

**Comment by christocracy** [comment]
It does seem to be out of a module's jurisdiction to dictate to the hosting application which version of gradle should be used, particularly so if there's not *very* clear documentation.

This bit me last week too.  Will be very frustrating for users with little experience with Gradle.

That being said, one should not place too much emphasis on "the React Native default".  This React Native default is designed around *Facebook's* interests -- not the end user's.  As we all know now, Facebook's interests tend not to align with one's own ;)

**Comment by mauron85** [comment]
>React Native default is designed around Facebook's interest

yeah, I think Chris you remember migration from 0.49 to 0.50 (or so). They broke almost all plugins and main reason was, it was simpler for their internal build system, which they don't even use in public versions of rn.

**Comment by christocracy** [comment]
The default React Native app is far too conservative.  A better model to design around, wrt compileSdk et al, is one generated by a native app in latest Android Studio, which will be gradle 3, latest compileSdk, etc.

However, a pure native developer doesn’t import nearly as many atomic 3rd party dependencies as an RN app.  Getting everybody aligned in this ecosystem is a problem.

**Comment by nazrdogan** [comment]
I was facing same issue. I created native Android project and get settings from there and applied  rn project. its working now [https://gist.github.com/nazrdogan/87c63e89a2bfd4cefee24990e4e7ed0e](gist)

**Comment by MarkOSullivan94** [comment]
> But I have personal issue with this gradle 3 switch. :) I just don't like it. IMO it's not worth the hassle of updating build.gradle, gradle-wrapper.properties... 

@mauron85 you have "personal issues" switching? Can you bare a thought for ANYONE downloading the latest version of Android Studio trying to get their project to compile using it and wont because it's not using Gradle 3.x?

RN works fine for me, I haven't touched RN's gradle settings at all, it was just RN-Maps in my case which was throwing build issues meaning that I couldn't build our Android app.

**Comment by mauron85** [comment]
>Can you bare a thought for ANYONE downloading the latest version of Android Studio trying to get their project to compile using it and wont because it's not using Gradle 3.x?

I'm opening all my gradle2 projects in Android Studio without any problems.

**Comment by MarkOSullivan94** [comment]
Yes and that is the expected behavior. Try and open a gradle 3 project with RN Maps using gradle 2.x, it'll be unable to build.

I have no idea why you are still using Gradle 2, there's no reason why RN or RN plugins should not be using gradle 3 and really all of them should be upgraded.

> builds up to 75% faster

Why would you want to endure the slow build times with Gradle 2 when Gradle 3 has improved it? That's the biggest thing to convince anyone working on a large project to upgrade.

https://docs.gradle.org/3.0/release-notes.html

**Comment by mauron85** [comment]
>I have no idea why you are still using Gradle 2, there's no reason why RN or RN plugins should not be using gradle 3 and really all of them should be upgraded.

1. compatibility reasons
2. many manual steps to migrate default react-native init template to gradle3 (not even covered by this PR, so actually no project will built)

**Comment by mauron85** [comment]
I'm closing this. As I see many downvotes from collaborators, without any trying to advocate why it was good switch (except MarkOSullivan94). IMO this attitude I don't like. You break stuff, becasue you cannot open project in Android Studio and accept PR without even mentioning that it will not work without migrating to gradle 3 ?  No notice, nothing? Come on. Giving up

**Comment by MarkOSullivan94** [comment]
1. Are those capability reasons caused by other plugins no updating to Gradle 3? If so, make an issue in their GitHub projects and state that they're using an old Gradle version. Heck, you could even be helpful and identify where they specify the gradle version and update it yourself, make a PR and help the community.
2. This can easily be fixed in a new version of RN where it'll default to Gradle 3.x and actually makes sense. I'll happily get working on that over the next week or so and it will mean you don't have to do any manual steps in upgrading your RN project

You are forgetting that a lot of projects using React Native aren't fully React Native, take into consideration that Instagram was a hybrid app with React Native components at one stage (not sure what state it is now) and I'm sure there's other Android projects out there like ours which is using a React Native component and so would be experiencing the same issue which I was having.

For now if you're having an issue with the gradle 3 specification and want to use the latest version of RN Maps you can manually revert it back:
- Change everything with `implementation` to `compile` in the build.gradle file for RN Maps, this can be found here: _<project dir>/node_modules/react-native-maps/lib/android/build.gradle_

Or if you don't want to do that why don't you just downgrade to RN Maps to the previous version where it was using Gradle 2?

**Comment by christocracy** [comment]
@MarkOSullivan94 It should be noted that @mauron85 is a plugin developer with several years' experience supporting a large audience of users.  This is not a simple case of him upgrading a handful of his *own* apps, he's likely experiencing a frustrating wave of support issues from his users.

**Comment by MarkOSullivan94** [comment]
If he is that's a very valid reason to raise an issue but nothing in his messages so far indicate that. I'm trying to justify why I did the PR and why it was merged by others into the project along with posting a solution for him for now.

Honestly this just seems like the RN project just needs to enforce Gradle 3.x and get every other plugin to upgrade after the next RN update.

**Comment by christocracy** [comment]
I think for now, it might be best to rollback to using `compile` instead of new `implementation` until clear, flawless upgrade instructions to Gradle 3 are in-place.

>Honestly this just seems like the RN project just needs to enforce Gradle 3.x and get every other plugin to upgrade after the next RN update.

The default React Native project is *completely* obsolete, designed for the interests of Facebook.  I wouldn't hold my breath on them supporting Gradle 3 any time soon.  This should **not** be treated as best-practice.  

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22        
    }
}
```

**Comment by jeffreymendez1993** [comment]
@christocracy I agree. The install instructions do not even work if you follow them with new versions of RN and gradle for android. I should not need to exclude any groups for gms that should be handled all by the library imo but then again I do not have much experience with android. Android seems to be always burning my time trying to get things to build / resolve dependancies. I think I am going to just spend a month learning groovy/gradle etc, because this is getting annoying. Only happens for projects using googles tools as in firebase gms and such.

**Comment by christocracy** [comment]
@jeffreymendez1993 avoiding `exclude` is precisely the purpose of my merged PR here:
https://github.com/react-community/react-native-maps/pull/2047

A number of other libraries are now implementing this mechanism.

**Comment by jamesone** [comment]
Are there any plans to rollback to `gradle2`?

I'm getting the same issues trying to use the latest rn-maps on rn 0.56

**Comment by abarisic86** [comment]
@jamesone with RN0.57 came with support for gradle3 so try to upgrade and install (latest instructions are not good)
