### ISSUE TITLE
'UIKit/UIKIt.h' file not found

### ISSUE THREAD

**Issue by gourav-singhal** [react-community/react-native-maps#2439]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment  

"react": "16.4.1",
"react-native": "0.56.0",
"react-native-maps": "^0.21.0"
Target Platform: iOS - 11.2 Simulator/iPhone 7
using GoogleMaps

### Steps to Reproduce

1.  Install react-native-maps from npm
2. Install pods 
3. Run .xcworkspace project

### Expected Behavior

Project should run error free

### Actual Behavior

Error in building project

'UIKit/UIKIt.h' file not found
/Google-Maps-iOS-Utils/src/Heatmap/GMUGradient.m:20:9: In file included from /Users/daffomac-04/Documents/projects/RNSampleMaps/ios/Pods/Google-Maps-iOS-Utils/src/Heatmap/GMUGradient.m:20:

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by averhulst** [comment]
I had this exact same issue today and this is what I arrived at: This library has a pod dependency on https://github.com/googlemaps/google-maps-ios-utils as defined in this project's podspec file that points to version 2.1.0. Version 2.1.0 of this google-maps-ios-utils library has a typo in the import that capitalizes the `i` in `kit` in `#import <UIKit/UIKit.h>` here: https://github.com/googlemaps/google-maps-ios-utils/blob/v2.1.0/src/Heatmap/GMUGradient.h#L16 

This has been fixed in a PR against their master branch but they haven't issued any subsequent releases so the problem remains (I think?) for people on case sensitive file systems. Here is the fix commit for reference: https://github.com/googlemaps/google-maps-ios-utils/commit/d5ca417617170b9a0e4e83964e961bfaf9b26f1f#diff-35557c027a0a457f95a20786d17682e5

What you can do in the short term is go into your Podfile and replace `pod 'Google-Maps-iOS-Utils'` with `pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/googlemaps/google-maps-ios-utils.git', :commit => 'd5ca417617170b9a0e4e83964e961bfaf9b26f1f'`. This will point the pod definition to the specific commit in the `google-maps-ios-utils` repo where the fix has been made and where the version is still marked as 2.1.0, satisfying `react-native-maps`'s dependency. This isn't a great solution and I have no idea if any of the commits between this fix and the latest release (in September 2017) will introduce any unexpected behavior but it seems to be working fine for me for simple maps and routes. 

I hope this helps somebody avoid the headache that I experienced.

**Comment by gourav-singhal** [comment]
@averhulst thanks for your help it worked for me.

**Comment by gkartalis** [comment]
@averhulst that was it! thank you very much

**Comment by mikeKane** [comment]
I am receiving this now also. It's weird because on one machine it works and on another it doesn't. 

Podfile output -> 

`Installing Crashlytics (3.12.0)
Installing DoubleConversion (1.1.6)
Installing Fabric (1.9.0)
Installing Folly (2018.10.22.00)
Installing Google-Maps-iOS-Utils (2.1.0)
Installing GoogleMaps (2.5.0)
Installing React (0.59.4)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing react-native-google-maps (0.24.2)
Installing react-native-maps (0.24.2)
Installing yoga (0.59.4.React)`

Xcode version 10.1

`fatal error: 'UIKit/UIKIt.h' file not found
#import <UIKit/UIKIt.h>
        ^~~~~~~~~~~~~~~
`

**Comment by mikeKane** [comment]
Are we able to reopen this issue?

**Comment by a-eid** [comment]
how were u able to resolve this??

**Comment by kceb** [comment]
I think this might work on macOS machines that are APFS case-insensitive, but not on mac machine volumes that are APFS case-sensitive

**Comment by kamalpreet11** [comment]
I recently upgraded my Macbook Pro with Catalina from Mojave and I am facing this issue on it.
My dependencies are:
"react": "16.11.0",
 "react-native": "0.62.2",
"react-native-maps": "0.27.1",

Pods: 
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

Following the solution given by @averhulst solves the problem but I think the underline issue is still there.

**Comment by ascholz81** [comment]
I just came across the same thing on a new system installation.   Using the above solution still in 2021 ! :-)
