### ISSUE TITLE
this.setOverflow("hidden");

### ISSUE THREAD

**Issue by GoodCloudRepair** [react-community/react-native-maps#2515]
在执行react-native是报了这个错误 
> Task :react-native-maps:compileDebugJavaWithJavac
/Users/wenkui/Documents/gator-work/codes/Gatorand/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/ViewAttacherGroup.java:23: 错误: 找不到符号
    this.setOverflow("hidden"); // Change to ViewProps.HIDDEN until RN 0.57 is base
        ^
  符号: 方法 setOverflow(String)
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误
----------------------------------------------------------
react-native：0.48.0
react:16.0.0-alpha.12
react-native-maps:0.21.0

How do I compile the past?

**Comment by sankalpgoibibo** [comment]
I am also getting this error. What is the solution?

**Comment by andikare** [comment]
me too , can you help me ?  What is the solution? @GoodCloudRepair and @sankalpgoibibo , thanks

**Comment by sankalpgoibibo** [comment]
@andikare This is due to compatibilty issue between the particular version of react-native and react-native-maps that you are using. 

From the docs:
> 
Due to the rapid changes being made in the React Native ecosystem, we are not officially going to support this module on anything but the latest version of React Native. With that said, we will do our best to stay compatible with older versions as much that is practical, and the peer dependency of this requirement is set to "react-native": "*" explicitly for this reason. If you are using an older version of React Native with this module though, some features may be buggy.

So go to the releases tab of react-native-maps, figure out the release date of your react-native version and try versions of maps released within the next one month. This fixed it for me. I was using 0.19.0 and downgraded myself to 0.18.3(RN version 0.49.3) to fix it.

Also you can comment out that particular line that is throwing exception and it seemed to work fine. You never know what breaks, so I would recommend the former method.

**Comment by andikare** [comment]
thankyou for the response @sankalpgoibibo , but still not work on my project, 
this is my Environment
react-native: 0.48.2
react: 16.0.0-alpha.12
android:
compileSdkVersion: 27
buildToolsVersion: 27.0.1
minSdkVersion 16
targetSdkVersion 22

and my package.json

"dependencies": {
    "multer": "^1.4.1",
    "native-base": "^2.3.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.2",
    "react-native-camera-roll-picker": "^1.2.3",
    "react-native-contacts": "^2.2.2",
    "react-native-encrypt-decrypt": "^1.0.0",
    "react-native-firebase": "^4.3.8",
    "react-native-fs": "^2.12.0",
    "react-native-gifted-chat": "^0.2.7",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-maps": "^0.22.1",

thank you

**Comment by pavlo-o-savchuk** [comment]
Ok, so I downgraded to npm install recat-native-maps@0.18.3 and it finally compiled for me. 
Can't imagine this kind of hell gonna be every time.
But thanks @harshitsaamu
