### ISSUE TITLE
Mapview is not draggable

### ISSUE THREAD

**Issue by raysmithdev** [react-community/react-native-maps#575]
I have installed the repo via npm & followed the tutorial however my map is not draggable (when the user wants to drag the map to a new region the map does nothing). Please see my map component below. Wondering if any1 else faces this problem. 

```
import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  Navigator
} from 'react-native';

import MapView from 'react-native-maps';

class Map extends Component {
  constructor(props) {
    super(props);
    this.onRegionChange = this.onRegionChange.bind(this);
    this.state = {
      region: {
        latitude: 37.78825,
        longitude: -122.4324,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      },
    };
  }

  onRegionChange(region) {
    this.setState({ region });
  }

  render() {
    return (
      <MapView
        style={styles.map}
        region={this.state.region}
        onRegionChange={this.onRegionChange}
      />
    );
  }
}

const styles = StyleSheet.create({
  map: {
   position: 'absolute',
   top: 0,
   left: 0,
   right: 0,
   bottom: 0,
 },
});

export default Map;
```

**Comment by chrisv95** [comment]
Intuitively, I would say this is caused because the component's actual size is 0x0 pixels (there is no _width_ or _height_ defined), while it is stretched from the top left corner to the bottom right corner.

Makes me think that given the fact that you do not actually touch the map, it does not drag.

Perhaps this may help:

- To your `import { ... } from 'react-native'` list, add `Dimensions`: [docs](https://facebook.github.io/react-native/docs/dimensions.html)
- Add `var {height, width} = Dimensions.get('window');` to your code.
- Then, change the style information of map into:

```map: {
   width: width,
   height: height
 }```

**Comment by raysmithdev** [comment]
@chrisv95 awesome man that worked, thanks a lot :)

**Comment by rborn** [comment]
Seems to be resolved. Closing.

**Comment by ref-prabhash** [comment]
i am facing the same problem
