### ISSUE TITLE
Link failed on 0.10.0

### ISSUE THREAD

**Issue by stephanemaillard** [react-community/react-native-maps#653]
After upgrading react-native-maps to 0.10.0, the linking failed because it can't find the following file

```
node_modules/react-native-maps/ios/AirGoogleMaps.xcodeproj/project.pbxproj
```

**Comment by aprihodko** [comment]
+1

**Comment by aprihodko** [comment]
Same is true for a v0.9.0

**Comment by Sciandra-Leva** [comment]
Looks like #656 is the same error, but since it is the older I'll write here: by looking at the docs regarding the [manual linking](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually) it doesn't link AirGoogleMaps BUT AIRMaps.

Soooo... should we trust the docs or the rnpm link action?

**Comment by cipick** [comment]
+1

**Comment by olegdizus** [comment]
+1

**Comment by ippa** [comment]
bitten by this as well

**Comment by gilbox** [comment]
There is no `AirGoogleMaps.xcodeproj` because if you are going to use GoogleMaps on iOS, including the `xcodeproj` file in your project file is not a valid way to compile. If you want to stick with MapKit, you shouldn't need any AirGoogleMaps-related files. If you want to use GoogleMaps then you should use [`Option 1`](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-1-cocoapods---same-as-the-included-airmapsexplorer-example) (or for the more adventurous, [Option 2](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-2-cocoapods----untested-way)).

**Comment by jgkim** [comment]
In addition to the above comment by @gilbox, if you don't want to use `CocoaPods`, you can install `Google Maps SDK for iOS` manually by following [the instruction](https://developers.google.com/maps/documentation/ios-sdk/start#step_2_install_the_sdk). Then, use the [`Option 3`](https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md#option-3-manually) and do the following:

1. Open your project in XCode

2. Drag the following folder into your project: `node_modules/react-native-maps/ios/AirGoogleMaps/`

3. Click on the project and go the Build Settings tab. Double click the text to the right of Header Search Paths and verify that it has `$(SRCROOT)/../../react-native/React` as well as the below:
    - `$(SRCROOT)/../../react-native/Libraries/ActionSheetIOS`
    - `$(SRCROOT)/../../react-native/Libraries/Geolocation`
    - `$(SRCROOT)/../../react-native/Libraries/Network`
    - `$(SRCROOT)/../../react-native/Libraries/Image`
    - `$(SRCROOT)/../../react-native/Libraries/LinkingIOS`
    - `$(SRCROOT)/../../react-native/Libraries/Settings`
    - `$(SRCROOT)/../../react-native/Libraries/Text`
    - `$(SRCROOT)/../../react-native/Libraries/Vibration`
    - `$(SRCROOT)/../../react-native/Libraries/WebSocket`

  if they aren't, then add them. This is so XCode is able to find the headers that the `AirGoogleMaps` source files are referring to by pointing to the header files installed within the react-native node_modules directory.

If you need to use `GoogleMaps`, you also need to set the API key in `AppDelegate.m` or elsewhere.

**Comment by gilbox** [comment]
According to Google:

> From version 1.10.0 onwards, the Google Maps SDK for iOS is available for installation only via CocoaPods.

That's why I don't support Option 3 with GoogleMaps on iOS.

**Comment by aprihodko** [comment]
@gilbox Why it does not work with a "react-native link"? I personally do not need a new Google Maps engine. But there is only one possible option to link a react-native-maps is to install v. 0.8.2, link it and then upgrade react-native-maps to a most recent version. But running a "react-native link" again will not work

**Comment by Sciandra-Leva** [comment]
imho @aprihodko has a point, given what you guys said: maybe `rnpm link` should not try at all linking Google Maps SDK for iOS - ofc this would also mean (maybe) modifying the installation docs saying that the GMaps SDK for iOS is only available using the other ways.

**Comment by alvelig** [comment]
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example. 
Try to check it out or build through the README.MD. If it does not help, let me know.
